global:
  scrape_interval: 5s

scrape_configs:
  - job_name: jobflow-api
    static_configs:
      - targets: ["api:8000"]
  - job_name: jobflow-worker
    static_configs:
      - targets: ["worker:9200"]
